# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies - DAL
      run: dotnet restore ./WelcomeHome/WelcomeHome.DAL/WelcomeHome.DAL.csproj
    - name: Restore dependencies - Services
      run: dotnet restore ./WelcomeHome/WelcomeHome.Services/WelcomeHome.Services.csproj
    - name: Restore dependencies - Web
      run: dotnet restore ./WelcomeHome/WelcomeHome.Web/WelcomeHome.Web.csproj
    - name: Build - DAL
      run: dotnet build WelcomeHome/WelcomeHome.DAL/WelcomeHome.DAL.csproj --configuration Release
    - name: Build - Services
      run: dotnet build WelcomeHome/WelcomeHome.Services/WelcomeHome.Services.csproj --configuration Release
    - name: Build - Web
      run: dotnet build WelcomeHome/WelcomeHome.Web/WelcomeHome.Web.csproj --configuration Release
    - name: Test
      run: dotnet test WelcomeHome/WelcomeHome.Services.Tests/WelcomeHome.Services.Tests.csproj --configuration Release --verbosity normal
